# Generated by Django 3.0.7 on 2020-06-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contingent_exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateN', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('amount_words', models.TextField()),
                ('station', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField()),
                ('IFSC_Code', models.CharField(max_length=12)),
                ('Bank_name_branch', models.TextField()),
                ('Bank_account_number', models.TextField()),
            ],
        ),
    ]
