# Generated by Django 3.0.7 on 2020-06-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contingent_exp', '0002_auto_20200625_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contingent_exp',
            old_name='sectio',
            new_name='dt',
        ),
    ]
