# Generated by Django 3.0.7 on 2020-06-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contingent_exp', '0003_auto_20200625_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contingent_exp',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='contingent_exp',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contingent_exp',
            name='dt',
        ),
        migrations.AddField(
            model_name='contingent_exp',
            name='amount1',
            field=models.DecimalField(decimal_places=2, default=2009, max_digits=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contingent_exp',
            name='amount2',
            field=models.DecimalField(decimal_places=2, default=2010, max_digits=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contingent_exp',
            name='amount3',
            field=models.DecimalField(decimal_places=2, default=4000, max_digits=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contingent_exp',
            name='description1',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contingent_exp',
            name='description2',
            field=models.TextField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contingent_exp',
            name='description3',
            field=models.TextField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contingent_exp',
            name='dt1',
            field=models.CharField(default=2009, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contingent_exp',
            name='dt2',
            field=models.CharField(default=2010, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contingent_exp',
            name='dt3',
            field=models.CharField(default=2002, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contingent_exp',
            name='totamount',
            field=models.DecimalField(decimal_places=2, default=8000, max_digits=1000),
            preserve_default=False,
        ),
    ]
