# Generated by Django 3.0.7 on 2020-06-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contingent_exp', '0004_auto_20200625_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contingent_exp',
            name='amount2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contingent_exp',
            name='amount3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contingent_exp',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contingent_exp',
            name='description3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contingent_exp',
            name='dt2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contingent_exp',
            name='dt3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
