# Generated by Django 3.0.7 on 2020-07-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contingent_exp', '0007_auto_20200701_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contingent_exp',
            name='Bank_account_number',
            field=models.CharField(max_length=16),
        ),
    ]
