# Generated by Django 3.0.7 on 2020-06-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_adv', '0002_travel_adv_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_adv',
            name='journeyclass',
            field=models.CharField(choices=[('Air(Business/Economy)', 'Air(Business/Economy)'), ('Train(1AC/2AC/3AC/ACC/SL/CC)', 'Train(1AC/2AC/3AC/ACC/SL/CC)'), ('Road (AC/Non-AC)', 'Road (AC/Non-AC)')], default='green', max_length=60),
        ),
    ]
