# Generated by Django 3.0.7 on 2020-06-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_adv', '0003_auto_20200626_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_adv',
            name='journeyclass',
            field=models.CharField(choices=[('Air(Business)', 'Air(Business)'), ('Air(Economy)', 'Air(Economy)'), ('Train(1AC)', 'Train(1AC)'), ('Train(2AC)', 'Train(2AC)'), ('Train(3AC)', 'Train(3AC)'), ('Train(ACC)', 'Train(ACC)'), ('Train(SL)', 'Train(SL)'), ('Train(CC)', 'Train(CC)'), ('Road (AC)', 'Road (AC)'), ('Road (Non-AC)', 'Road (Non-AC)')], default='green', max_length=60),
        ),
    ]
