# Generated by Django 3.0.7 on 2020-06-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_adv', '0005_auto_20200626_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel_adv',
            name='accommodation_charges',
        ),
    ]
