# Generated by Django 3.0.7 on 2020-06-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_adv', '0006_remove_travel_adv_accommodation_charges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel_adv',
            old_name='totamount',
            new_name='Total_amount',
        ),
    ]
