# Generated by Django 3.0.7 on 2020-07-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_adv', '0007_auto_20200629_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_adv',
            name='Bank_account_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='travel_adv',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
    ]
