# Generated by Django 3.0.7 on 2020-07-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_adv', '0008_auto_20200702_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Travel_adv_choices',
        ),
        migrations.AlterField(
            model_name='travel_adv',
            name='Bank_account_number',
            field=models.CharField(max_length=16),
        ),
    ]
