# Generated by Django 3.0.7 on 2020-06-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=120)),
                ('net_claimed', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('dt1', models.TextField(max_length=10)),
                ('cashmemo1', models.TextField()),
                ('firmname1', models.TextField()),
                ('purpose1', models.TextField()),
                ('amount1', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('dt2', models.TextField(blank=True, max_length=10, null=True)),
                ('cashmemo2', models.TextField(blank=True, null=True)),
                ('firmname2', models.TextField(blank=True, null=True)),
                ('purpose2', models.TextField(blank=True, null=True)),
                ('amount2', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('dt3', models.TextField(blank=True, max_length=10, null=True)),
                ('cashmemo3', models.TextField(blank=True, null=True)),
                ('firmname3', models.TextField(blank=True, null=True)),
                ('purpose3', models.TextField(blank=True, null=True)),
                ('amount3', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('dt4', models.TextField(blank=True, max_length=10, null=True)),
                ('cashmemo4', models.TextField(blank=True, null=True)),
                ('firmname4', models.TextField(blank=True, null=True)),
                ('purpose4', models.TextField(blank=True, null=True)),
                ('amount4', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('dt5', models.TextField(blank=True, max_length=10, null=True)),
                ('cashmemo5', models.TextField(blank=True, null=True)),
                ('firmname5', models.TextField(blank=True, null=True)),
                ('purpose5', models.TextField(blank=True, null=True)),
                ('amount5', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('totamount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('amount_words', models.TextField()),
                ('IFSC_Code', models.CharField(max_length=12)),
                ('Bank_name_branch', models.TextField()),
                ('Bank_account_number', models.TextField()),
            ],
        ),
    ]
