# Generated by Django 3.0.7 on 2020-06-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reimbursement',
            old_name='totamount',
            new_name='Total_amount',
        ),
    ]
