# Generated by Django 3.0.7 on 2020-07-01 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0002_auto_20200629_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='employee_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
