# Generated by Django 3.0.7 on 2020-07-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0003_reimbursement_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='dt1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='dt2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='dt3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='dt4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='dt5',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
