# Generated by Django 3.0.7 on 2020-07-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telephone_Reim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('employee_id', models.CharField(max_length=12)),
                ('designation', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('amount_words', models.TextField()),
                ('department', models.CharField(max_length=120)),
                ('month', models.CharField(max_length=15)),
                ('cred_month', models.CharField(max_length=15)),
                ('IFSC_Code', models.CharField(max_length=12)),
                ('Bank_name_branch', models.TextField()),
                ('Bank_account_number', models.CharField(max_length=15)),
            ],
        ),
    ]
