# Generated by Django 3.0.7 on 2020-07-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephone', '0002_auto_20200702_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephone_reim',
            name='Bank_account_number',
            field=models.CharField(max_length=16),
        ),
    ]
