# Generated by Django 3.0.7 on 2020-06-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cert_A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
                ('employee_id', models.CharField(max_length=12)),
                ('patient_name', models.CharField(max_length=120)),
                ('patient_age', models.IntegerField()),
                ('employee_rel', models.CharField(max_length=120)),
                ('doctor_address', models.TextField()),
                ('disease', models.CharField(max_length=120)),
                ('dt1', models.CharField(max_length=10)),
                ('dt2', models.CharField(max_length=10)),
                ('Consult_dt1', models.CharField(max_length=10)),
                ('Consult_fee1', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('IIS_fee1', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('Consult_dt2', models.CharField(max_length=10)),
                ('Consult_fee2', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('IIS_fee2', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('Med_name1', models.CharField(max_length=120)),
                ('Med_qty1', models.IntegerField()),
                ('Med_price1', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('Med_CashMemoNo1', models.CharField(max_length=120)),
                ('Med_name2', models.CharField(max_length=120)),
                ('Med_qty2', models.IntegerField()),
                ('Med_price2', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('Med_CashMemoNo2', models.CharField(max_length=120)),
                ('DiagTest_name1', models.CharField(max_length=120)),
                ('DiagTest_center1', models.CharField(max_length=120)),
                ('DiagTest_price1', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('DiagTest_name2', models.CharField(max_length=120)),
                ('DiagTest_center2', models.CharField(max_length=120)),
                ('DiagTest_price2', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('RefDoc', models.CharField(max_length=120)),
                ('totamount', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
    ]
