# Generated by Django 3.0.7 on 2020-06-26 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cert_a', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert_a',
            name='station',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
