# Generated by Django 3.0.7 on 2020-06-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert_a', '0002_cert_a_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cert_a',
            old_name='DiagTest_price1',
            new_name='Diagnostic_Test_price1',
        ),
        migrations.RenameField(
            model_name='cert_a',
            old_name='DiagTest_price2',
            new_name='Diagnostic_Test_price2',
        ),
        migrations.RenameField(
            model_name='cert_a',
            old_name='IIS_fee1',
            new_name='Injection_fee1',
        ),
        migrations.RenameField(
            model_name='cert_a',
            old_name='IIS_fee2',
            new_name='Injection_fee2',
        ),
        migrations.RenameField(
            model_name='cert_a',
            old_name='Med_price1',
            new_name='Price1',
        ),
        migrations.RenameField(
            model_name='cert_a',
            old_name='Med_price2',
            new_name='Price2',
        ),
        migrations.RenameField(
            model_name='cert_a',
            old_name='Med_qty1',
            new_name='Quantity1',
        ),
        migrations.RenameField(
            model_name='cert_a',
            old_name='Med_qty2',
            new_name='Quantity2',
        ),
        migrations.RenameField(
            model_name='cert_a',
            old_name='totamount',
            new_name='Total_amount',
        ),
    ]
