# Generated by Django 3.0.7 on 2020-07-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_a', '0003_auto_20200629_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert_a',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
    ]
