# Generated by Django 3.0.7 on 2020-06-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta_bill',
            name='arr_date_1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='arr_date_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='arr_date_3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='arr_station_2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='arr_station_3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='dep_date_1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='dep_date_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='dep_date_3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='dep_station_2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='dep_station_3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='encl_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='fare_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='fare_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='other_exp_amount_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='other_exp_amount_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='other_exp_billdetails_2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='other_exp_billdetails_3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='other_exp_item_2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='other_exp_item_3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='pymt_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='ticket_no_2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='ta_bill',
            name='ticket_no_3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
