# Generated by Django 3.0.7 on 2020-06-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_bill', '0003_auto_20200627_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ta_bill',
            name='payment_voucher_no',
        ),
        migrations.RemoveField(
            model_name='ta_bill',
            name='pymt_date',
        ),
    ]
