# Generated by Django 3.0.7 on 2020-07-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_bill', '0005_auto_20200629_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta_bill',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
    ]
