# Generated by Django 3.0.7 on 2020-07-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_bill', '0006_auto_20200701_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta_bill',
            name='Bank_account_number',
            field=models.CharField(max_length=16),
        ),
    ]
