# Generated by Django 3.0.7 on 2020-07-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_bill', '0007_auto_20200702_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ta_bill',
            old_name='Admissible_Amount',
            new_name='Eligible_Amount',
        ),
    ]
