# Generated by Django 3.0.7 on 2020-07-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_bill', '0008_auto_20200704_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ta_bill',
            name='Total_amount_A',
        ),
        migrations.RemoveField(
            model_name='ta_bill',
            name='Total_amount_B',
        ),
    ]
