# Generated by Django 3.0.7 on 2020-07-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_bill', '0009_auto_20200705_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ta_bill',
            name='AdvanceDraw',
        ),
        migrations.RemoveField(
            model_name='ta_bill',
            name='Eligible_Amount',
        ),
        migrations.RemoveField(
            model_name='ta_bill',
            name='Net_Claim_Admissible',
        ),
        migrations.RemoveField(
            model_name='ta_bill',
            name='To_be_paid_by_iith',
        ),
        migrations.RemoveField(
            model_name='ta_bill',
            name='To_be_recovered_by_iith',
        ),
        migrations.RemoveField(
            model_name='ta_bill',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ta_bill',
            name='amt_in_words',
        ),
    ]
